### ISSUE TITLE
Dynamic position bug

### ISSUE THREAD

**Issue by DerOrakel** [basdelfos/beta-osd-v2#10]
Hi @basdelfos 

Using the latest commit when the mode indicator is enabled and battery voltage gets to the warning level  and starts to blink the mode indicator jumps left and right whenever battery voltage blinks out and in again.

![pict0020](https://cloud.githubusercontent.com/assets/21347918/18420539/33fd4efa-7875-11e6-800f-8524ab70d672.gif)

Autocam works nice here with a HS1190 (Foxeer Arrow) ntsc.

As for the order of indicators i would prefer the old order: RSSI, VBAT, FTIMER, MODE

regards
ron

**Comment by basdelfos** [comment]
Yeah, I already noticed the same issue in one of my flights during the weekend. When the voltage is below the low voltage warning threshold, it starts blinking. The blinking causes the voltage not to display and the mode is placed on the position of the voltage. 

I already fixed it earlier this evening, like 15 minutes ago :smile:. Look in the development branch.

Good to know that autocam works, the sourcecode is left-over from the original MWOSD code and I didn't test it yet.

I will fix the order, probably changed it on accident while adding the dynamic position feature.

**Comment by DerOrakel** [comment]
Great compiled and flashed latest development commit and will test it monday.

**Comment by basdelfos** [comment]
Actually I made a bug in mistake (should have tested it...). It is fixed now in de development branch.

**Comment by DerOrakel** [comment]
Seems to work fine, not sure about the flied order tought I flashed the latest Dev commit but order still was  rssi, ftimer, vbat (mode was disabled this time). Have to take a look at it again.

**Comment by basdelfos** [comment]
Strange, just tested the latest development branch and the order is RSSI, VBAT, TIMER, MODE.

![img_0469](https://cloud.githubusercontent.com/assets/334779/18454054/82a3ca7a-7942-11e6-941a-d2a169628e49.jpg)

**Comment by DerOrakel** [comment]
Using the latest commit field order is as it was originally, so maybe my last flash went wrong or i was just making up things. I don't know it's correct now :)
