### ISSUE TITLE
Where is the EEP file as requested in the wiki?

### ISSUE THREAD

**Issue by llambkin** [basdelfos/beta-osd-v2#9]
The wiki mentions to put an EEP file into the AVRDUDESS program, I have downloaded everything on the site, and it is missing.

**Comment by basdelfos** [comment]
Oeps...that's a bug in the instructions. I will correct this. With version 2 there is no EEP file anymore, you will only need to flash the HEX file. 

The default settings are stored in the EEPROM on first startup after flashing (and when selecting RESET in de OSD menu). You will see the message 'INITIALIZING...' in the OSD when this action is performed. At the same time the font is also stored in the display chip.
